---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-nginx-alice
  labels:
    name: app
    color: blue
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      color: blue
      name: app
  template:
    metadata:
      name: blue
      labels:
        name: app
        color: blue
    spec:
      containers:
      - image: docker.io/wakabh56/hwakabhcitest:f16c1cce142663289047d39f624221ba4bd00dc2
        name: nginx-alice
        ports:
          - containerPort: 80

